spring:
  redis:
    host: 192.168.160.133
    port: 6379
    password:
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
  datasource:
    url: jdbc:mysql://localhost:3306/voice_print_recognition?serverTimezone=GMT%2B8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#设置上传文件大小限制
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

mybatis:
  # 指定 mapper.xml 的位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
  type-aliases-package: club.jming.voiceprintrecognition.pojo
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true